###
POST http://localhost:8000/api/assets/
Content-Type: application/json

{
    "name": "Test",
    "description": "Test",
    "asset_type": "OTHER",
    "is_active": true
}

###
DELETE http://localhost:8000/api/assets/3/
Content-Type: application/json

###
POST http://localhost:8000/api/stock/price/fetch/
Content-Type: application/json

{
}

###
POST http://localhost:8000/api/backtest/static-allocation/
Content-Type: application/json

{
    "allocations": [
        {
            "ticker": "SPY",
            "weight": 0.6
        },
        {
            "ticker": "TLT",
            "weight": 0.4
        }
    ]
}