# Generated by Django 5.1.7 on 2025-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='티커')),
                ('type', models.CharField(choices=[('stock', '주식'), ('etf', 'ETF')], max_length=10, verbose_name='종류')),
                ('market', models.CharField(choices=[('kospi', 'KOSPI'), ('nasdaq', 'NASDAQ'), ('nyse', 'NYSE')], max_length=10, verbose_name='시장')),
            ],
            options={
                'verbose_name': '주식',
                'verbose_name_plural': '주식',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'type'), name='unique_ticker_type')],
                'unique_together': {('ticker', 'type')},
            },
        ),
    ]
