# Generated by Django 5.1.7 on 2025-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='listed_date',
            field=models.DateField(blank=True, null=True, verbose_name='상장일'),
        ),
    ]
