# Generated by Django 5.1.7 on 2025-05-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_listed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='저가')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='수정 종가')),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stock.stock', verbose_name='주식')),
            ],
            options={
                'verbose_name': '가격',
                'verbose_name_plural': '가격',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
