# Generated by Django 5.1.7 on 2025-05-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='adj_close_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='수정 종가'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='종가'),
        ),
    ]
