# Generated by Django 5.1.7 on 2025-07-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['-created_at'], 'verbose_name': '전략', 'verbose_name_plural': '전략'},
        ),
    ]
