# Generated by Django 5.1.7 on 2025-07-17 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_alter_strategy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='allocations',
            field=models.JSONField(blank=True, help_text='Asset allocations for the strategy in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='cash_ticker',
            field=models.CharField(default='CASH', help_text='Ticker symbol for cash asset in the strategy', max_length=20),
        ),
        migrations.AddField(
            model_name='strategy',
            name='cash_weight',
            field=models.FloatField(default=0.0, help_text='Weight of cash in the strategy (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='strategy',
            name='include_cash',
            field=models.BooleanField(default=False, help_text='Whether to include cash in the strategy'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='rebalance_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Rebalance frequency for the strategy', max_length=20),
        ),
    ]
