# Generated by Django 5.1.7 on 2025-07-17 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_strategy_allocations_strategy_cash_ticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='cash_ticker',
            field=models.CharField(blank=True, default='CASH', help_text='Ticker symbol for cash asset in the strategy', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='cash_weight',
            field=models.FloatField(blank=True, default=0.0, help_text='Weight of cash in the strategy (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
