# Generated by Django 5.1.7 on 2025-07-15 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_return', models.FloatField(help_text='Total Return Percentage')),
                ('cagr', models.FloatField(help_text='Compound Annual Growth Rate')),
                ('max_drawdown', models.FloatField(help_text='Maximum Drawdown')),
                ('volatility', models.FloatField(help_text='Volatility')),
                ('sharpe_ratio', models.FloatField(help_text='Sharpe Ratio')),
                ('sortino_ratio', models.FloatField(help_text='Sortino Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to='strategy.strategy')),
            ],
            options={
                'verbose_name': 'Backtest Result',
                'verbose_name_plural': 'Backtest Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
