# Generated by Django 5.1.7 on 2025-07-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backtestresult',
            options={'ordering': ['-created_at'], 'verbose_name': '백테스트 결과', 'verbose_name_plural': '백테스트 결과'},
        ),
    ]
