# Generated by Django 5.1.7 on 2025-07-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_alter_backtestresult_options'),
        ('strategy', '0004_alter_strategy_cash_ticker_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BacktestResult',
            new_name='BacktestStat',
        ),
        migrations.AlterModelOptions(
            name='backteststat',
            options={'ordering': ['-created_at'], 'verbose_name': '백테스트 요약', 'verbose_name_plural': '백테스트 요약'},
        ),
    ]
