# Generated by Django 5.1.7 on 2025-07-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_rename_backtestresult_backteststat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backteststat',
            name='description',
            field=models.TextField(blank=True, help_text='백테스트 결과에 대한 설명을 입력하세요.', verbose_name='결과 설명'),
        ),
        migrations.AddField(
            model_name='backteststat',
            name='name',
            field=models.CharField(default='mock', max_length=255, verbose_name='결과 이름'),
            preserve_default=False,
        ),
    ]
